web:
  extends:
    file: common.yml
    service: web
  volumes:
    - .:/code
  ports:
    - "5001:5000"
  links:
    - db
  command: python manage.py runserver -h 0.0.0.0 -p 5000 -d -r
  environment:
    - DATABASE_URL=mysql://root:secretpassword@db/test
db:
  extends:
    file: common.yml
    service: db
  ports:
    - "8989:3306"
  volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./mysql_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: secretpassword
    MYSQL_DATABASE: epic
    MYSQL_USER: user
    MYSQL_PASSWORD: password
